import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const REPO = "C:/Users/wyatt/Projects/pastrypirates";
const { isGameCode } = require(REPO + "/.claude/hooks/lib/game-code.cjs");
const all = execFileSync("git", ["ls-files"], { cwd: REPO, encoding: "utf8" }).split("\n").filter(Boolean);
const g = all.filter(isGameCode);
console.log("tracked total:", all.length, "-> counted as GAME:", g.length);
console.log("index.html present:", g.includes("index.html"));
console.log("src/ files:", g.filter(f => f.startsWith("src/")).length);
console.log("assets/ files:", g.filter(f => f.startsWith("assets/")).length);
console.log("package.json present:", g.includes("package.json"));
console.log("package-lock.json present:", g.includes("package-lock.json"));
console.log("scripts/ leaked in:", g.filter(f => f.startsWith("scripts/")).length);
console.log(".planning/ leaked in:", g.filter(f => f.startsWith(".planning/")).length);
console.log("paths with backslash:", all.filter(f => f.includes("\\")).length);
console.log("first 8 game paths:", g.slice(0, 8));
