import { gameTreeHash } from "../lib/game_tree_hash.mjs";
import { REPO } from "../lib/chrome.mjs";
const t0 = Date.now();
const h1 = gameTreeHash(REPO);
const t1 = Date.now();
const h2 = gameTreeHash(REPO);
console.log("hash1:", h1);
console.log("hash2:", h2);
console.log("deterministic:", h1 === h2);
console.log("elapsed ms first call:", t1 - t0);
