#!/usr/bin/env node
/* GATE: the resize measurement must be able to READ every picture in the library.
 *
 *   node scripts/qa/display_size_reads_every_picture_check.mjs
 *
 * WHAT WENT WRONG, MEASURED 2026-09-02. `.planning/ASSET-DISPLAY-SIZES.md` is the one answer this
 * project has to Wyatt's INBOX-20260901T1335Z part (c) — "everything else should be resized and
 * compressed according to its maximum pixel size in the real gameplay". It is generated by
 * `scripts/qa/asset_display_size_probe.mjs`, whose report loop reads each file's intrinsic size and
 * then does `if (!nat) continue;`.
 *
 * That size reader handled PNG and JPEG. Then the compression pass renamed ~200 files to `.webp` —
 * and every one of them fell through `continue` and VANISHED from the report. Not listed as
 * unmeasured, not counted in the totals, absent. The report kept its confident heading while
 * silently covering a fraction of the library, INCLUDING the heaviest file in the game.
 *
 * WHY A GATE AND NOT A FIXED READER. This is the project's own recurring shape: an instrument whose
 * subject is narrower than the thing it is believed to cover (`docs/HARD-WON-LESSONS.md` §3 — a
 * gate aimed at the wrong tree is not silent, it is reassuring). The reader will go narrow again the
 * next time a family is re-encoded into a format nobody thought about — AVIF is the obvious next
 * one. What must not happen again is that going narrow is INVISIBLE.
 *
 * WHAT IT ASSERTS, and it is derived, never a list:
 *   for every image file under `assets/` that the probe's own walk would collect —
 *     `intrinsicSize()` returns real dimensions for it.
 *
 * So it fails the moment a format arrives that the reader cannot read, and it names the files.
 * RED-PROOFED by deleting the WebP branch from `scripts/lib/imagesize.mjs`: it names **53 files,
 * 2.09 MB — more than HALF the 3.89 MB library, the board among them.**
 *
 * IT DELIBERATELY NAMES NO FORMAT AND NO FILE. A gate holding its own copy of the answer cannot
 * fail when the answer changes.
 */
"use strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { intrinsicSize } from "../lib/imagesize.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

/* THE SAME WALK THE PROBE MAKES, and the same extension pattern — copied deliberately so this gate
   asks about exactly the set the report is built from, rather than a set of its own choosing. */
const PATTERN = /\.(png|jpe?g|webp|gif|avif)$/i;
const files = [];
(function walk(d) {
  if (!fs.existsSync(d)) return;
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (PATTERN.test(e.name)) files.push(p);
  }
})(path.join(ROOT, "assets"));

let fail = false;
const say = (ok, label) => { console.log(`${ok ? "OK" : "FAIL"} -- ${label}`); if (!ok) fail = true; };

/* A check with nothing to check has told you about ITSELF, not about the game. */
say(files.length > 0, `assets/ holds ${files.length} image file(s) — an empty walk would pass on nothing`);

const blind = [];
for (const f of files) {
  const size = intrinsicSize(fs.readFileSync(f));
  if (!size || !(size.w > 0) || !(size.h > 0)) blind.push(f);
}

const bytes = blind.reduce((s, f) => s + fs.statSync(f).size, 0);
say(blind.length === 0,
  blind.length === 0
    ? `every one of the ${files.length} pictures reports its own intrinsic size`
    : `${blind.length} picture(s) cannot be read, ${(bytes / 1048576).toFixed(2)} MB — they are DROPPED from the resize measurement`);

if (blind.length) {
  const byExt = new Map();
  for (const f of blind) {
    const ext = path.extname(f).toLowerCase();
    byExt.set(ext, (byExt.get(ext) || 0) + 1);
  }
  console.log("");
  for (const [ext, n] of [...byExt].sort((a, b) => b[1] - a[1]))
    console.log(`   ${ext}  ${n} file(s)`);
  console.log("");
  for (const f of blind.slice(0, 8)) console.log(`   ${path.relative(ROOT, f).replace(/\\/g, "/")}`);
  if (blind.length > 8) console.log(`   ...and ${blind.length - 8} more`);
  console.log("");
  console.log("These files are silently absent from .planning/ASSET-DISPLAY-SIZES.md, which still");
  console.log("presents itself as the measured maximum size of every picture in the game.");
  console.log("Teach scripts/lib/imagesize.mjs to read the format — do not narrow the walk to hide them.");
}

process.exit(fail ? 1 : 0);
