#!/usr/bin/env node
// scripts/measure_race_spread.mjs
//
// MEASURES RACE_SPREAD (3/src/engine/index.js) — the scatter, in turns, between a mid-voyage
// finish prediction and the finish that actually happened. The v3 race planner reads every
// pairwise race off a logistic curve over the margin in turns; RACE_SPREAD is that curve's σ,
// and this script is what makes it a measurement instead of a taste.
//
// Method: replay a seeded corpus with every seat on the INCUMBENT brain (planTurnClassic — the
// dynamics the spread describes must not be generated by the constant being measured). At the
// top of each captain's turn, record
//
//     predicted finish = round + 1 + contested tour (turnsToWin3, rivals' depletion included)
//
// and afterwards compare against the round that captain actually finished baking in. The residual
// standard deviation over every (captain, round) sample whose captain went on to finish is the
// number. Re-run this if the movement, dock, battle or bake rules ever change.
//
//   node scripts/measure_race_spread.mjs [games]

import { Game, roundCfg } from "../3/src/engine/index.js";

const GAMES = +(process.argv[2] || 300);
const STRATS = ["pirate", "trader", "balanced", "rusher"];

// every seat on the incumbent, so the measured dynamics are the shipped ones
Game.prototype.planTurn = function (p) { return this.planTurnClassic(p); };

const TAKE = Game.prototype.takeTurn;
let samples = [];   // {p, round, pred} per turn, resolved against finishes after each game

Game.prototype.takeTurn = function (p, w, st) {
  if (!p.done && !p.baking) {
    const ctx = this.raceContext3(p);
    const t = this.turnsToWin3(p, ctx);
    if (t < 90) {
      this._spreadSamples.push({ idx: p.idx, round: this.round, pred: this.round + 1 + t });
      // the quantity raceScore3 actually reads is the PAIRWISE margin — my contested tour against
      // each rival's public ETA — so that difference is what gets calibrated, not either estimator
      // alone (they carry different biases: the tour is contention-pessimistic, the rival plan is
      // recipe-optimistic, and only their gap decides anything)
      for (const e of ctx.plans)
        this._marginSamples.push({ p: p.idx, q: e.q.idx, predMargin: e.plan.eta - (t + 1) });
    }
  }
  return TAKE.call(this, p, w, st);
};

// `done` is set by endBakeDay (bakes resolve together at the end of a day), not by bakeAttempt —
// so the finish round is read off that transition.
const ENDDAY = Game.prototype.endBakeDay;
Game.prototype.endBakeDay = function () {
  const before = this.players.map(p => p.done);
  const r = ENDDAY.call(this);
  this.players.forEach((p, i) => { if (!before[i] && p.done) this._finishRound[i] = this.round; });
  return r;
};

const residuals = [], marginOutcomes = [];
for (let s = 1; s <= GAMES; s++) {
  const g = new Game({ ...roundCfg(STRATS), bakeoff: true }, s * 7919, true);
  g._spreadSamples = []; g._finishRound = {}; g._marginSamples = [];
  g.play();
  for (const smp of g._spreadSamples) {
    const fin = g._finishRound[smp.idx];
    if (fin === undefined) continue;          // never finished — no truth to compare against
    residuals.push(fin - smp.pred);
  }
  /* "both finished" almost never happens — the voyage ends when the winner bakes — so residuals
     of the margin are unmeasurable without crushing selection bias (the only observable pairs
     are same-day co-finishers, whose true margin is ~0 by construction). What IS observable for
     every pair involving the eventual winner is the OUTCOME the curve exists to predict: did p
     finish before q. So bias and spread are fitted by maximum likelihood on those outcomes. */
  const w = g.winner != null ? g.winner : (g.finishOrder && g.finishOrder[0]);
  if (w == null) continue;
  for (const smp of g._marginSamples) {
    if (smp.p === w) marginOutcomes.push({ m: smp.predMargin, won: 1 });
    else if (smp.q === w) marginOutcomes.push({ m: smp.predMargin, won: 0 });
  }
}

const stats = a => {
  const n = a.length, m = a.reduce((x, y) => x + y, 0) / n;
  return { n, m, sd: Math.sqrt(a.reduce((x, y) => x + (y - m) * (y - m), 0) / n) };
};
const mine = stats(residuals);
console.log(`${GAMES} games`);
console.log(`my tour:  ${mine.n} samples, residual mean ${mine.m.toFixed(2)}, sd ${mine.sd.toFixed(2)} (+ = voyages run longer than predicted)`);

// MLE of P(p beats q) = sigma((m + bias) / spread) over observed outcomes, by grid search — the
// exact functional form raceScore3 uses, fitted to the exact question it answers.
let bestLL = -Infinity, bestB = 0, bestS = 3;
for (let b = -6; b <= 8; b += 0.25) {
  for (let s = 1; s <= 15; s += 0.25) {
    let ll = 0;
    for (const o of marginOutcomes) {
      let z = (o.m + b) / s; if (z > 30) z = 30; if (z < -30) z = -30;
      const pr = 1 / (1 + Math.exp(-z));
      ll += Math.log(o.won ? pr : 1 - pr);
    }
    if (ll > bestLL) { bestLL = ll; bestB = b; bestS = s; }
  }
}
console.log(`pairwise outcomes (winner-involved pairs): ${marginOutcomes.length} samples`);
console.log(`MLE fit of sigma((margin + RACE_BIAS) / RACE_SPREAD):`);
console.log(`  RACE_BIAS   ${bestB.toFixed(2)}`);
console.log(`  RACE_SPREAD ${bestS.toFixed(2)}`);
// calibration table: does the fitted curve track the observed win rate by margin bucket?
const buckets = new Map();
for (const o of marginOutcomes) {
  const k = Math.max(-8, Math.min(8, Math.round(o.m / 2) * 2));
  const b = buckets.get(k) || { n: 0, w: 0 }; b.n++; b.w += o.won; buckets.set(k, b);
}
console.log(`  margin bucket -> observed win rate (n) | fitted`);
for (const k of [...buckets.keys()].sort((a, b) => a - b)) {
  const b = buckets.get(k);
  const fit = 1 / (1 + Math.exp(-(k + bestB) / bestS));
  console.log(`  ${String(k).padStart(4)} -> ${(100 * b.w / b.n).toFixed(0).padStart(3)}% (${b.n}) | ${(100 * fit).toFixed(0)}%`);
}
